# Prompt Log — журнал работы над тестовым заданием «Exchange Order»

> Документ ведётся непрерывно. Фиксируется **всё**: входные данные от заказчика,
> принятые решения, промпты, выданные агентам, и их рассуждения/выводы.
> Формат записи: `## [N] <дата/этап> — <источник> — <суть>`.

---

## [0] Метаданные

| Поле | Значение |
|------|----------|
| Проект | Внутренний модуль «Кошелёк пользователя» → экран обмена валют |
| Репозиторий | `d:\Project\bidzaar` |
| Дата старта | 2026-08-07 |
| Исполнитель | Мультиагентная система (оркестратор + 6 специализированных агентов) |
| Заказчик | sk@nadipay.io |

---

## [1] 2026-08-07 — ЗАКАЗЧИК — Первичная постановка задачи

Дословно полученное сообщение:

> Привет. Нам необходимо сделать тестовое задание описание находится в `/d:/Project/bidzaar/docs/BRD.md`
> для реализации и полного анализа необходимых действий необходимо подключить агентов `d:/Project/bidzaar/docs/`
> Дополнительно информация по тестовому заданию лежит в папке `docs`.
>
> При анализе и проведении работ необходимо отдельно создать файл `promtlog.md` и записывать в него
> всю полученную информацию от меня и рассуждения агентов.
>
> При Описании API для взаимодействия с приложением закладывае что это финтех приложение, работающее
> с криптовалютой, за апи точно будет сервис KYC (если хочешь можешь посмотреть welID), сервис курсов,
> сервис лимитов и комиссий, аккаунтинг, крипто провайдер для получения информации по ордерам с бирж,
> users, скоринг, сервис нотификации. Их реализовывать не надо, только описать получение информации
> от них в сторону приложения в полном объёме.
>
> В приложении данные хардкод, не используем авторизацию, необходимо сконцентрироваться на странице
> обмена. И детальном описании документации как описано в задании.

### Извлечённые из сообщения требования (разбор оркестратора)

| # | Требование | Тип | Влияние на объём работ |
|---|-----------|-----|------------------------|
| R-01 | Основа — `docs/BRD.md` | Констрейнт | Все 5 артефактов из §11 BRD обязательны |
| R-02 | Подключить агентов из `docs/agents/` | Процесс | Работа выполняется мультиагентно, роли берутся из готовых персон |
| R-03 | Вести `promtlog.md` | Процесс | Этот файл; пополняется на каждом этапе |
| R-04 | Домен = финтех + **криптовалюта** | Домен | BRD говорит про «валюты» вообще; заказчик уточнил крипто-контур → нужны network/chain, on-chain fee, крипто-провайдер |
| R-05 | 8 внешних сервисов за API | Архитектура | KYC (WebID), Rates, Limits&Fees, Accounting, Crypto Provider, Users, Scoring, Notifications |
| R-06 | Внешние сервисы **не реализовывать** | Скоуп | Только контракты: что и в каком объёме приложение **получает** от них |
| R-07 | Описать получение информации «в полном объёме» | Глубина | Полные модели данных, коды ошибок, таймауты, ретраи, деградация |
| R-08 | Данные в приложении — hardcode | Скоуп прототипа | Никакого бэкенда; моки в слое `src/api/` |
| R-09 | Авторизация не используется | Скоуп прототипа | Нет login/session; `userId` зашит в фикстуры |
| R-10 | Фокус — страница обмена | Скоуп прототипа | Один экран, без роутинга по прочим разделам кошелька |
| R-11 | Детальная документация как в задании | Качество | SDD, OpenAPI, Gherkin, UX/UI-прототип, диаграммы |

### Замечание оркестратора по R-04 (конфликт с BRD)

BRD §3 задаёт дефолтную пару **RUB → USDT**, т.е. фиат↔крипто. Уточнение заказчика про крипто-провайдера
подтверждает: система гибридная (fiat + crypto). Следствия, которых **нет** в исходном BRD и которые
добавлены осознанно:

1. Для крипто-активов появляется измерение **network/chain** (USDT существует в TRC-20, ERC-20, BEP-20 —
   это разные балансы и разные сетевые комиссии). Design Brief §Exchange Summary уже требует строку
   `Network` — это подтверждает гипотезу.
2. Точность (`decimals`) у активов разная: RUB = 2, USDT = 6, BTC = 8. Все денежные величины —
   **строки с десятичной записью**, не `float` (потеря точности недопустима в финтехе).
3. Появляются регуляторные проверки, которых нет в BRD §5, но которые обязательны для крипто-финтеха:
   **KYC-уровень**, **лимиты по обороту**, **скоринг/AML**. Они добавлены в цепочку валидации
   (см. `docs/00-canonical-model.md` §6).

### Замечание оркестратора по «welID»

Заказчик написал «welID» — с высокой вероятностью имеется в виду **WebID** (WebID Solutions GmbH,
немецкий провайдер идентификации: VideoIdent / eID / AutoIdent, применяется для BaFin-совместимого
онбординга). Контракт KYC-сервиса спроектирован по модели именно такого провайдера:
асинхронная сессия верификации + webhook-нотификация о смене статуса + уровни верификации.
Это **предположение**; оно явно помечено в `docs/api/INTEGRATIONS.md` как ASSUMPTION-01.
Если имелся в виду другой вендор — меняется только маппинг полей, форма контракта сохраняется.

---

## [2] 2026-08-07 — ОРКЕСТРАТОР — Уточняющие вопросы заказчику и ответы

| Вопрос | Варианты | **Выбор заказчика** |
|--------|----------|--------------------|
| Форма UX/UI-прототипа | React+Vite+TS / один HTML-файл / оба | **React + Vite + TypeScript** |
| Язык документации | RU (UI и код — EN) / всё EN / билингва | **Русский; UI и код — English** |
| Глубина описания внешних сервисов | Контракт-документ + OpenAPI-стабы / только раздел в SDD / только стабы | **Отдельный контракт-документ + OpenAPI-стабы** |

Решения зафиксированы как обязательные для всех агентов.

---

## [3] 2026-08-07 — ОРКЕСТРАТОР — Разбор входных документов

Прочитаны и учтены:

| Файл | Роль в работе | Ключевое, что вытянуто |
|------|---------------|------------------------|
| `docs/BRD.md` | Первоисточник | §4 функциональные требования, §5 шесть ограничений, §7 структура экрана, §8 поведение, §10 четыре сервиса, §11 пять артефактов |
| `docs/Product Context.md` | Контекст | «Одно действие, один экран, одно подтверждение»; скоуп = только создание заявки |
| `docs/Design Brief.md` | Бриф дизайнера | Карточка 440px, EN-подписи, палитра, типографика Inter, 8 UI-состояний, строка `Network` в Summary |
| `docs/System Design Brief.md` | Бриф архитектора | C4, Mermaid (Sequence + Component), точки отказа, жизненный цикл заявки, масштабирование, **без деталей БД** |
| `docs/API Brief.md` | Бриф бэкенд-архитектора | OpenAPI **3.1**, `POST /exchange-orders`, описание каждого поля, business errors, примеры успеха и ошибок, REST (не SOAP/RPC) |
| `docs/Gherkin Brief.md` | Бриф аналитика | ≥1 happy + **≥5** негативных; перечислены 7 обязательных негативных кейсов; бизнес-язык |

### Конфликты между документами и их разрешение (оркестратор)

| # | Конфликт | Решение | Обоснование |
|---|----------|---------|-------------|
| C-01 | BRD §11.3 требует «минимум два Negative Path», Gherkin Brief — «не менее пяти» и перечисляет семь | Реализуем **все 7** перечисленных | Более строгое требование поглощает менее строгое |
| C-02 | BRD §7 задаёт русские подписи («Обмен валют», «Обменять»), Design Brief — английские («Exchange», «Exchange Now») | UI на **английском** по Design Brief; русские формулировки BRD приведены в UX/UI-спеке как таблица соответствия | Design Brief — более поздний и более детальный документ по UI; выбор заказчика в [2] это подтверждает |
| C-03 | BRD §7 — карточка 420–480px, Design Brief — «около 440px» | **440px** | 440 входит в диапазон BRD, конфликта по сути нет |
| C-04 | BRD §10 перечисляет 4 сервиса, заказчик — 8 | Итог: **9 внешних систем** (4 из BRD + 8 заказчика, с дедупликацией Exchange Rate Service ↔ «сервис курсов», Wallet Service ↔ Accounting) | См. карту в `docs/00-canonical-model.md` §3 |
| C-05 | BRD §4 требует «быстрый выбор процента 25/50/75/100», Design Brief дополнительно требует кнопку `MAX` | ~~Чипы 25/50/75 % + `MAX` вместо чипа 100 %~~ → **пересмотрено:** чипы 25/50/75/100 % **и** кнопка `MAX` | **Первоначальное решение было неверным.** Я счёл чип 100 % и `MAX` дублирующими и убрал первый. Дизайн-триада (D-04) и Business Analyst независимо пришли к тому, что оба брифа требуют обоих контролов и это разные точки входа: чипы — набор долей под полем, `MAX` — действие рядом с балансом, к которому оно относится. Прототип исправлен |
| C-06 | BRD §4 требует чипы «процент от баланса» и Design Brief — кнопку `MAX`, но BRD §5 не определяет, берётся комиссия сверху или изнутри суммы | Режим комиссии зафиксирован как **`INCLUDED_IN_SOURCE`**: комиссия удерживается внутри введённой суммы; проверка баланса — `fromAmount ≤ available` | При комиссии «сверху» `MAX`/`100 %` всегда давали бы `INSUFFICIENT_FUNDS` (`fromAmount + fee > available`), т.е. требования BRD §4 и Design Brief были бы нереализуемы. Цена решения: пользователь получает меньше, чем «сумма × курс», поэтому строка `Fee` в Summary обязательна. Полный вывод — `docs/00-canonical-model.md` §5.3 |

---

## [4] 2026-08-07 — ОРКЕСТРАТОР — Состав агентов и маршрутизация

Подключены персоны из `docs/agents/` (установлены в `.claude/agents/` для повторного использования).

| Агент (персона) | Источник | Задача в этом проекте | Артефакт |
|-----------------|----------|----------------------|----------|
| CTO / Orchestrator | `09-orchestrator.md` | Разрешение конфликтов, канонический домен, приёмка | `00-canonical-model.md`, этот лог |
| Software Architect | `engineering-software-architect.md` | High-Level SDD, C4, Mermaid, точки отказа, ЖЦ заявки | `docs/SDD.md` |
| API Tester → Backend Architect | `testing-api-tester.md` | OpenAPI 3.1 основного API + 8 интеграционных контрактов | `docs/api/**` |
| Business Analyst (по Gherkin Brief) | `specialized-document-generator.md` | Feature-файл: happy + 7 негативных | `docs/features/exchange-order.feature` |
| UX Researcher | `design-ux-researcher.md` | Сценарии, болевые точки, требования к состояниям | вклад в `docs/UX-UI-Spec.md` |
| UX Architect | `design-ux-architect.md` | Дизайн-токены, сетка, CSS-архитектура, состояния | вклад в `docs/UX-UI-Spec.md` |
| UI Designer | `design-ui-designer.md` | Визуальная спецификация карточки, микровзаимодействия | вклад в `docs/UX-UI-Spec.md` |
| Code Reviewer | `engineering-code-reviewer.md` | Приёмка прототипа и консистентности артефактов | раздел [9] этого лога |

**Принцип маршрутизации** (из `09-orchestrator.md`, «Route to Expert»): каждый артефакт делает
профильный агент; оркестратор заранее фиксирует общий домен, чтобы агенты не разъехались
в терминологии и кодах ошибок.

**Принцип «Verify API Assumptions»** (принцип #8 CTO-001) применён к WebID: предположение о вендоре
помечено явно, а не подано как факт.

---

## [5] 2026-08-07 — АГЕНТ «Business Analyst» — Gherkin-сценарии

**Задача:** feature-файл по `Gherkin Brief.md`, минимум 1 happy + 7 обязательных негативных, бизнес-язык,
арифметика строго по фикстурам канона §10 и правилам §5.3.

**Артефакты:** `docs/features/exchange-order.feature` (322 строки), `docs/features/README.md` (240 строк).

**Результат:** 22 сценария, 31 исполняемый случай с учётом `Примеры`. Итог: 7 happy, 1 alternative, 14 negative.

### Рассуждения агента — разрешённые расхождения

| # | Расхождение | Решение агента | Оценка оркестратора |
|---|-------------|----------------|---------------------|
| G-1 | Ввод `0`: регулярка §5.1 его допускает, но шаг 11 §6 отнёс бы к `AMOUNT_BELOW_MINIMUM` | Ноль = `VALIDATION_ERROR` (шаг 1), т.к. сообщение «Минимальная сумма 500.00» при вводе нуля дезориентирует | **Принято.** Внесено в прототип: явная проверка `isZero` перед проверкой границ в `createQuote` |
| G-2 | BRD §5 («сумма > баланса → отказ») vs BRD §4 (чип 100 %) | Разрешено каноном §5.3 (`INCLUDED_IN_SOURCE`); сценарий 3 «Обмен всего баланса кнопкой MAX» делает это **проверяемым** требованием | **Принято.** Ровно тот эффект, ради которого решение принималось |
| G-3 | Фикстура §10.5 даёт дневной остаток `320 000 RUB`, что недостижимо при балансе `25 450 RUB` — сценарий лимита сработал бы на нехватке средств | Использован сценарный переключатель `LIMIT_HIT` (§10.6): остаток `5 000 RUB`, сумма `10 000 RUB` — нарушено ровно одно условие | **Принято.** Хороший разбор: сценарий должен нарушать ровно одно правило, иначе он проверяет порядок проверок, а не само правило |
| G-4 | BRD §11 «минимум два негативных» vs Gherkin Brief «не менее пяти», перечислено семь | Принято строгое требование | Совпадает с решением C-01 оркестратора |
| G-5 | Идемпотентность (§9 канона) — технический механизм | Переформулирована в бизнес-терминах: «двойное нажатие → ровно одна заявка, резерв однократный», без упоминания `Idempotency-Key` | **Принято.** Требование брифа о бизнес-языке соблюдено |

### Проверенная арифметика (пересчитана агентом вручную и скриптом на Decimal)

`RUB→USDT`, курс `0.010638297872`, комиссия 0.35 %, minFee `10.00`, RUB = 2 знака, USDT = 6 знаков:

| fromAmount | feeRaw | feeAmount (ROUND_UP) | netFromAmount | toAmountRaw | **toAmount (ROUND_DOWN)** |
|-----------|--------|----------------------|---------------|-------------|---------------------------|
| `10000.00` | `35.0000` | `35.00` | `9965.00` | `106.01063829448` | **`106.010638`** |
| `6362.50` (25 %) | `22.26875` | `22.27` | `6340.23` | `67.44925531699056` | **`67.449255`** |
| `12725.00` (50 %) | `44.5375` | `44.54` | `12680.46` | `134.89851063398112` | **`134.898510`** |
| `19087.50` (75 %) | `66.80625` | `66.81` | `19020.69` | `202.34776595097168` | **`202.347765`** |
| `25450.00` (MAX) | `89.0750` | `89.08` | `25360.92` | `269.79702126796224` | **`269.797021`** |

Дрейф курса (1 USDT = 94.50 → курс `0.010582010582`, дрейф **0.529 %** > порога 0.20 %):
`10000.00` → fee `35.00` → net `9965.00` → **`105.449735`**

Swap `USDT→RUB`, курс `93.60`, 0.35 %, minFee `0.50` USDT:
`106.010638` → feeRaw `0.371037233` → **сработал минимум** → fee `0.500000` → net `105.510638` → **`9875.79`**
Это единственный пример, где комиссия определяется минимумом, а не процентом — ценная проверка граничного случая.

### Действие оркестратора по итогам

Мок `ratesService` в прототипе был приведён в соответствие со сценарием 15: коэффициент дрейфа
изменён с `1.004` (курс улучшается) на `0.9947` (курс **ухудшается**, −0.53 %). Обоснование:
улучшившийся курс не требует подтверждения пользователя, поэтому не проверяет путь
«кнопка заблокирована до принятия новых условий» из BRD §8.

### Сознательно не покрыто (с обоснованием агента)

- `EXCHANGE_SERVICE_UNAVAILABLE` — наблюдаемое пользователем поведение неотличимо от
  `RATE_SERVICE_UNAVAILABLE` (тот же баннер, та же неактивная кнопка). Различие кодов — предмет
  контракта API, а не приёмочного сценария. **Оркестратор: принято**, но в прототипе сценарий
  `EXCHANGE_DOWN` оставлен — он проверяет момент отказа (submit, а не quote), что в UI различимо.
- 16 прочих кодов каталога §7 — вне BRD §5 и вне брифа, нет сценарных переключателей в §10.6.
- BRD §6, §7, §9 (палитра, вёрстка, адаптивность) — визуальные требования, не выражаются как
  поведение; их место в UX/UI-спецификации.

---

## [6] 2026-08-07 — АГЕНТ «Software Architect» — System Design Document

**Задача:** High-Level SDD по `System Design Brief.md`: C4, Mermaid (Sequence + Component), точки отказа,
обработка ошибок, ЖЦ заявки, бизнес-проверки, масштабирование. Без деталей БД.

**Артефакт:** `docs/SDD.md` — **1627 строк**, 12 диаграмм Mermaid
(2 C4-flowchart, 1 component, 6 sequenceDiagram, 1 stateDiagram-v2, 1 error-flow, 1 trust-boundary),
23 раздела. Синтаксис диаграмм проверен агентом скриптом: ID узлов латиницей, лейблы в кавычках.

### Принятые ADR (14, каждый с названной ценой решения)

| ADR | Суть |
|-----|------|
| ADR-01 | BFF-слой между SPA и доменом |
| ADR-02 | Двухфазный протокол `quote → order` вместо одношагового |
| ADR-03 | `Idempotency-Key` с окном хранения 24 ч |
| ADR-04 | Деньги — decimal-строки на всём пути |
| ADR-05 | Синхронная цепочка проверок 1..19; асинхронно только S9 |
| ADR-06 | Кеш курсов 1 с + окно stale 10 с + флаг `degraded` |
| ADR-07 | Circuit breaker отдельно на каждую внешнюю систему |
| ADR-08 | Hold создаётся после проверок 1..17 и до регистрации в S8 |
| ADR-09 | Compliance-First: шаги 13→16 идут раньше проверки баланса (17) |
| ADR-10 | ULID для `orderId`, UUID для `quoteId` |
| ADR-11 | Quote Store — отдельное TTL-хранилище с compare-and-set |
| ADR-12 | Уведомление через transactional outbox |
| ADR-13 | Orchestrator — модульный монолит, а не набор микросервисов |
| ADR-14 | Request/response вместо WebSocket-стрима курсов |

### Точки отказа (19)

`FM-01` S1 · `FM-02` S2 (stale запрещён) · `FM-03` S3 · `FM-04` S4 · `FM-05` S5 · `FM-06` S6 ·
`FM-07` S7 · `FM-08` S8 · `FM-09` S9 · `FM-10` Quote Store · `FM-11` таймаут и бюджет latency ·
`FM-12` hold без заявки · `FM-13` рассинхрон часов и TTL · `FM-14` дубль по двойному клику ·
`FM-15` гонка «истечение TTL vs submit» · `FM-16` переполнение Quote Store · `FM-17` каскадный отказ ·
`FM-18` Idempotency Store · `FM-19` отравленный кеш каталога.

### Рассуждения агента — расхождения и их разрешение

| # | Расхождение | Решение агента | Оценка оркестратора |
|---|-------------|----------------|---------------------|
| A-1 | Задание оркестратора требовало показать `Order Service` контейнером, канон §3 относит S8 к внешним системам | В пользу канона: S8 за периметром, наш деплой-юнит — `OrderRegistrar` + `S8Adapter`. `ASSUMPTION-08` | **Принято.** Агент верно предпочёл нормативный документ формулировке задания |
| A-2 | Канон §11 писал `POST /exchange-quotes`, §9 и §12 — `/v1/exchange/quotes` | Принят `/v1/exchange/quotes` | **Принято, канон исправлен** оркестратором: §11 приведён к `/v1/exchange/quotes` |
| A-3 | Бюджет p95 ≤ 900 мс несовместим с суммой таймаутов §11 (1000+1000+1000+1500+2000 мс последовательно) | Параллельный фан-аут и кеши объявлены **обязательными**, введён сквозной дедлайн; остаточный риск вынесен в `FM-11` | **Принято.** Это ровно та проверка, ради которой SDD и пишется: бюджет и таймауты нельзя задавать независимо |
| A-4 | S7 Crypto Provider классифицирован как `Degradable`, но не фигурирует ни в одном шаге §6 | S7 обогащает котировку (статус сети, `estimatedCompletionAt`), блокирующим гейтом не является. `ASSUMPTION-10`: если остановка сети должна блокировать обмен — нужен новый шаг и новый код ошибки | **Принято.** Агент не стал изобретать код ошибки, а поднял вопрос — верное поведение |
| A-5 | §6 шаг 2 указывает источник идемпотентности «локально», но при stateless-масштабировании он обязан быть распределённым | Трактовано как «внутри нашего периметра»; Idempotency Store — отдельный контейнер; его отказ → fail-closed (`FM-18`) | **Принято** |
| A-6 | §8 содержит статус `REJECTED`, но при синхронной валидации заявка до S8 не доходит — отказ возвращается ошибкой, а не записью | `ASSUMPTION-04`: `REJECTED` не материализуется в S8, попытка фиксируется в audit trail | **Принято.** Важное уточнение: диаграмма ЖЦ описывает домен, а не таблицу |
| A-7 | Кеш курсов 1 с (§11) против Rate Lock TTL 15 с (§2) | Не конфликт: TTL кеша управляет построением **новых** котировок, TTL котировки — сроком уже выданного обязательства | **Согласен.** Формулировка внесена в SDD §9 и §12 |
| A-8 | Open circuit 30 с против потолка stale 10 с | За пределами 10 с все котировки уходят в `503`; показано в SD5 как штатное поведение, не как дефект | **Принято** |
| A-9 | BRD §10 `Exchange Service` | По канону это наш Orchestrator, поэтому на C4 L1 его нет; код `EXCHANGE_SERVICE_UNAVAILABLE` используется как обобщённый `503` при отказе Blocking-цепочки | **Принято** |

### ASSUMPTION-01..13 (что требует подтверждения заказчиком)

WebID как вендор KYC · профиль нагрузки · идемпотентность на стороне S6/S8 · не материализуем `REJECTED`
в S8 · окно stale-курса 10 с согласовано с риском · fail-closed при отказе S3 · срок хранения audit trail ·
владение Order Service · путь `POST /v1/exchange/quotes` · роль S7 вне цепочки 1..19 · лимит 3 авто-рефрешей
котировки · circuit breaker per-instance · grace-зона 1 с перед `expiresAt`.

### Сознательно не включено (с обоснованием агента)

- Детали схемы БД, индексы, DDL — прямой запрет `System Design Brief`; вместо этого только
  «какое состояние где живёт» (§19.2).
- Полные JSON-схемы и контракты S1..S9 — чтобы не дублировать OpenAPI; §14 даёт сводку со ссылкой на `docs/api/`.
- C4 L4 / деплоймент (k8s, сети, регионы) — не запрошено, на решения в скоупе не влияет.
- Новые коды ошибок и статусы не изобретались; непокрытые каталогом ситуации помечены как ASSUMPTION.
- Проектирование за границей `PENDING` — показано только серым на диаграмме ЖЦ.

---

## [7] 2026-08-07 — АГЕНТЫ «UX Researcher + UX Architect + UI Designer» — UX/UI-спецификация

**Задача:** одна триада агентов последовательно в трёх ролях: исследование → техническая основа →
визуальная спецификация. Требование: документ, по которому разработчик реализует экран без единого
уточняющего вопроса.

**Артефакт:** `docs/UX-UI-Spec.md` — **2319 строк**, 21 раздел + 2 приложения
(сверенные расчёты, журнал расхождений).

### Что получено

- **14 состояний машины экрана**, 36 переходов `T-01…T-36` с побочными эффектами,
  6 кросс-состояний среды (`visibilitychange`, `online/offline`, `beforeunload`),
  8 инвариантов `M-1…M-8`. Диаграмма Mermaid `stateDiagram-v2`.
- **Полный набор дизайн-токенов** — сырая палитра → семантические алиасы → компонентные значения.
- **15 компонентов** с полными сигнатурами props.
- **15 юзабилити-рисков** `R-01…R-15` с рекомендациями.
- Инвентарь из 29 состояний интерфейса (включая не-happy).

### Проверка контраста (реальные расчёты по WCAG 2.1)

| Пара | Коэффициент | Вердикт |
|------|-------------|---------|
| `#111827` / `#FFFFFF` | 17.74 | AAA |
| `#6B7280` / `#FFFFFF` | 4.83 | AA |
| `#FFFFFF` / `#2563EB` | 5.17 | AA |
| `#DC2626` / `#FFFFFF` | 4.83 | AA |
| `#16A34A` / `#FFFFFF` | **3.30** | **AA не пройден для текста** |

**Найденный дефект палитры BRD/Design Brief и его исправление.** Зелёный `#16A34A`, предписанный
обоими брифами для «успешных действий», не проходит WCAG AA для текста (3.30 при требуемых 4.5).
Решение агента: разделить токен на два — `#16A34A` остаётся заливкой и графикой (там порог 3:1
выполняется), для текста введён `#15803D` (5.02). Дополнительно:

- `#6B7280` на `#F3F4F6` даёт 4.39 → поверхность `#F3F4F6` объявлена **нетекстовой**;
  вторичный текст допускается только на `#FFFFFF`, `#F8F9FB` (4.59), `#F9FAFB` (4.63).
- Для amber-текста `#D97706` (3.19) отвергнут в пользу `#B45309` (5.02).
- Disabled-кнопка `#6B7280` на `#D1D5DB` даёт 2.71 — формально вне требований WCAG, но введён
  инвариант «disabled ⇒ обязателен видимый текст-причина» серым по белому (4.83).

**Оценка оркестратора:** принято полностью. Это ровно то, ради чего в цепочку ставится дизайнер
с мандатом на доступность: бриф заказчика содержал недоступную пару цветов, и агент не выполнил
его буквально, а исправил с обоснованием.

### Рассуждения агентов — расхождения и разрешения

| # | Расхождение | Решение | Оценка оркестратора |
|---|-------------|---------|---------------------|
| D-01 | Язык подписей: RU (BRD §7) ↔ EN (Design Brief) | **EN**, плюс таблица соответствия RU↔EN на 24 строки в §20 | Совпадает с C-02 |
| D-02 | Ширина карточки 420–480 (BRD) ↔ «около 440» (Design Brief) | **ровно 440 px** | Совпадает с C-03 |
| D-03 | 4 строки инфоблока (BRD §7) ↔ 5 строк с `Network` (Design Brief) | **5 строк**; «Итоговая сумма» BRD = `Estimated Receive` | Принято, обоснование через §5.5 канона |
| D-04 | Чипы `25/50/75/100` (BRD §4) ↔ кнопка `MAX` (Design Brief) | **оба контрола**; `MAX` — функциональный синоним `100 %`, но живёт рядом с балансом | **Отменяет моё раннее решение C-05.** Я предлагал убрать чип 100 % как дублирующий; агент и Gherkin-агент независимо пришли к тому, что оба брифа требуют обоих контролов и это разные точки входа. Прототип исправлен: чипы 25/50/75/100 под полем + кнопка `MAX` у баланса |
| D-05 | «Курс действует 15 секунд» читается как дедлайн | Формулировка `Rate updates in Ns`; TTL не изменён | Принято, снимает риск R-01 |
| D-06 | «Кнопка активна только после всех проверок» (Design Brief) | Добавлен обязательный видимый текст-причина под кнопкой | Принято, снимает R-15 |
| D-07 | Зелёный `#16A34A` | Разделён на fill и text из-за WCAG | См. выше |
| D-08 | BRD §8 «блокировать при смене курса» ↔ риск тревожности | Блокировка **только** при дрейфе > 0.20 %; истечение TTL без дрейфа = тихое автообновление | **Принято.** Согласуется с решением ADR-06 архитектора и §11 канона |
| D-09 | 6 состояний в Design Brief | Развёрнуто в 14 состояний машины + 29 состояний инвентаря | Принято |
| D-10 | `Exchange Service` как внешняя система (BRD §10) | Следуем канону: внутренний оркестратор | Совпадает с A-9 архитектора |

### Юзабилити-риски (15)

`R-01` таймер как источник тревоги · `R-02` подмена курса под пальцем в момент нажатия ·
`R-03` непонимание, что комиссия внутри суммы · `R-04` читаемость длинных крипто-чисел ·
`R-05` ошибочный выбор network для USDT · `R-06` чип 100 % даёт «неровное» число ·
`R-07` held-баланс · `R-08` Compliance-First сбивает с толку · `R-09` двойной submit ·
`R-10` read-only поле читается как сломанное · `R-11` тупик на неподдерживаемой паре ·
`R-12` мёртвая котировка после возврата из фона · `R-13` две цифры получения ·
`R-14` направление курса и спред · `R-15` немая disabled-кнопка.

---

## [8] 2026-08-07 — ОРКЕСТРАТОР — Реализация прототипа и его верификация

Прототип написан оркестратором по спецификациям агентов; агенты в код не писали, чтобы избежать
рассинхрона между документом и реализацией.

### Приведение кода к спецификации

1. **Токены.** Первая версия `tokens.css` использовала собственные имена переменных. После получения
   §7.2 UX-спеки файл переписан так, чтобы имена и значения совпадали с документом **буквально** —
   иначе ревьюер, сверяющий спеку с кодом, видит два разных языка. Переименовано ~60 переменных,
   шкала spacing перестроена с 4px-базы на шкалу спеки (`--space-1: 2px … --space-12: 64px`).
2. **Чипы процентов.** Исправлено по D-04 (см. выше).
3. **Дрейф курса.** Коэффициент в моке изменён с `1.004` на `0.9947`, чтобы курс двигался
   **против** пользователя и совпадал со сценарием 15 Gherkin.
4. **Ввод нуля.** Добавлена явная проверка `isZero` перед проверкой минимума — по решению G-1.

### Верификация (`npm run verify`)

| Проверка | Что делает | Результат |
|----------|-----------|-----------|
| `typecheck` | `tsc -b`, strict, `noUnusedLocals`, `noUnusedParameters` | без ошибок |
| `verify:money` | 22 ассерта арифметики против чисел из feature-файла | **22/22 PASS** |
| `verify:render` | SSR-рендер дерева компонентов + двух поздних состояний | **17/17 PASS** |
| `npm run build` | Vite production build | 64 модуля, 272 kB JS / 24 kB CSS |

Браузерного инструмента в среде нет, поэтому вместо скриншота сделан серверный рендер: он реально
исполняет дерево компонентов и сверяет числа на экране с feature-файлом. Проверено, что при загрузке
рендерится скелетон, что у заблокированной кнопки есть текст-причина, что Summary содержит все 5 строк
Design Brief и что панель успеха показывает `PENDING`, а не «Completed» — заявка принята, но не исполнена.

### Инцидент среды (для честности отчёта)

Две параллельно запущенные установки npm перетёрли друг друга: `TAR_ENTRY_ERROR ENOENT`, затем
`EBUSY` на `esbuild.exe` и повреждённые `lib.dom.d.ts` / `lib.es2018.regexp.d.ts`. Устранено полной
очисткой `node_modules` и однократной установкой. Урок зафиксирован: не запускать npm-установки
конкурентно в одном каталоге.

---

## [9] 2026-08-07 — АГЕНТ «API Architect» — OpenAPI 3.1 и контракты интеграций

**Задача:** спецификация основного API по `API Brief.md` + описание в полном объёме того, что
приложение получает от 9 внешних систем. Сами системы не реализуются.

**Артефакты (11 файлов, ~23 400 строк):**

| Файл | Строк |
|------|-------|
| `docs/api/exchange-orders.openapi.yaml` | 3636 |
| `docs/api/INTEGRATIONS.md` | 1714 |
| `docs/api/integrations/accounting.yaml` | 2680 |
| `docs/api/integrations/order-service.yaml` | 2527 |
| `docs/api/integrations/notifications.yaml` | 2496 |
| `docs/api/integrations/limits-fees.yaml` | 2438 |
| `docs/api/integrations/kyc-webid.yaml` | 2203 |
| `docs/api/integrations/exchange-rates.yaml` | 2141 |
| `docs/api/integrations/scoring-aml.yaml` | 2099 |
| `docs/api/integrations/crypto-provider.yaml` | 2091 |
| `docs/api/integrations/users.yaml` | 1381 |

**Валидация агентом:** все 10 YAML прогнаны через официальную JSON Schema OpenAPI 3.1
(`openapi_spec_validator`) — 10/10 OK. Дополнительно: 0 битых `$ref`, 0 `type: number`,
0 устаревших `nullable:`, 0 неиспользуемых `components.examples`.

**Покрытие каталога ошибок:** 43 именованных примера (12 успешных + 31 ошибочный).
Все **29/29** кодов §7 имеют пример. `SCORING_REVIEW_REQUIRED` подан не как `ProblemDetails`,
а как поле `review.code` в успешном `202` — потому что ошибкой не является.

### Рассуждения агента — расхождения D-01…D-13 и решения оркестратора

| # | Расхождение, найденное агентом | Что сделал агент | **Решение оркестратора** |
|---|-------------------------------|------------------|--------------------------|
| D-01 | Каталог §7 не содержит кода для «заявка не найдена». `QUOTE_NOT_FOUND` — про котировку, `VALIDATION_ERROR` — про `400` | Ввёл `ORDER_NOT_FOUND` как **кандидата** и намеренно вынес его **за** закрытый enum, чтобы его нельзя было принять за ратифицированный. Поднял вопрос наверх | **O-1: ратифицировать.** Внесено в §7 канона, в enum `ErrorCode`, в `ERROR_CATALOG` прототипа и в `getOrder`. Формулировки «кандидат» в спеке заменены. Образцовое поведение: агент не залатал дыру неточным кодом, а показал её |
| D-02 | Нет кода для `USER_NOT_FOUND` от S1 | Маппинг в `VALIDATION_ERROR` (400), а не 404 | **O-2: принято.** 404 раскрывал бы факт существования учётной записи — прямое противоречие Compliance First |
| D-03 | S4 умеет возвращать `YEARLY_LIMIT_EXCEEDED`, кода в §7 нет | Схлопнул в `LIMIT_EXCEEDED_MONTHLY`; пользователь получит неточный текст | **O-3: принято как техдолг.** Годовых лимитов нет в §10.5, поэтому не блокирует. Занесено в открытые вопросы |
| D-04 | §11 канона писал `POST /exchange-quotes`, задание — `/v1/exchange/quotes` | Взял путь из задания | Совпадает с A-2 архитектора; канон уже исправлен |
| D-05 | `GET /v1/wallet/balances` — единственное число против §9 | Оставил: `wallet` — singleton-ресурс; побочно снимает вектор IDOR, так как в пути нет `walletId` | **O-4: принято.** Аргумент про IDOR сильнее формального правила именования |
| D-06 | `SCORING_REVIEW_REQUIRED` числится в «каталоге ошибок», но ошибкой не является | Оставлен в enum, но никогда не приходит в `ProblemDetails` | **Принято** |
| D-07 | §4.5 канона описывает `ExchangeOrder` неполно | Добавил `netFromAmount` (нужен клиенту для проверки инварианта I1), `inverseRate`, `rateSource`, `updatedAt`, `statusReason`, `version` | **Принято.** `netFromAmount` в ответе — верное решение: клиент может проверить арифметику сервера, не пересчитывая её самостоятельно |
| D-08 | §11 не задаёт таймауты для S7 и S9 | 800 / 1000 мс, помечено ASSUMPTION | Принято |
| D-09 | Правило «stale 10 с → 503» конфликтовало бы с классом `Degradable` у S7 | Отнесено только к S5 | **Принято.** Правило и вправду писалось про курсы |
| D-10 | §10.5 не задаёт границу суток и валюту нормализации лимитов | UTC + RUB | **O-5: провизорно принято, вынесено заказчику.** Для резидента `AE` (§10.1) сброс дневного лимита придётся на 04:00 по местному времени. Агент предложил поднять до блокирующего — согласен, см. OPEN-1 |
| D-11 | `kycValidUntil: 2027-04-30` без времени против §9 (ISO-8601 с мс) | `2027-04-30T23:59:59.000Z` | **O-6: принято, канон и фикстуры прототипа исправлены.** Конец дня, а не начало: верификация действует весь последний день |
| D-12 | BRD §10 называет `Exchange Service` внешним, канон — внутренним | Следует канону | Совпадает с A-9 архитектора и D-10 дизайн-триады |
| D-13 | S8 обязан вернуть `201` (ресурс создан), а §7 требует `202` для `MANUAL_REVIEW` | Разделено по уровням: S8 → `201`, наш API → `202` | **Принято.** Уровни контрактов не обязаны совпадать |

### Самокритика агента и что с ней сделано

| # | Претензия агента к собственному контракту | Решение оркестратора |
|---|-------------------------------------------|----------------------|
| 1 | `acceptRateChange` — полумера: булев флаг покрывает дрейф внутри порога, но не даёт осознанно принять больший проскок. Правильнее `maxAcceptableRate` — пользователь фиксирует худший приемлемый курс | **Согласен, в бэклог.** Не делаем сейчас: этого нет ни в брифах, ни в UI-спеке, и это меняло бы экран, заданный Design Brief |
| 2 | Порог дрейфа 0.20 % одинаков для всех пар. Для `RUB→USDT` разумно, для `RUB→BTC` даст `RATE_CHANGED` почти на каждом подтверждении | **Согласен.** Порог должен быть per-pair и приходить из S4. OPEN-2 |
| 3 | Обратный расчёт не поддержан: поле «Получаю» read-only, `POST /quotes` принимает только `fromAmount`. Первый запрос «хочу ровно 100 USDT» потребует ломающего изменения | **Согласен.** Рекомендация: заложить поле `side` в запрос котировки заранее, чтобы не ломать контракт позже. OPEN-4 |
| 4 | D-10 стоит поднять до блокирующего | **Принято**, см. OPEN-1 |
| 5 | Нет `GET /v1/exchange-orders` (список). Клиент, потерявший `orderId` при обрыве после `POST`, не может его найти | **Согласен, что это дыра в восстановлении состояния.** §1 канона выносит историю из скоупа, поэтому агент прав, что не добавил. Рекомендация: `GET /v1/exchange-orders?idempotencyKey=…` — этого достаточно, полная история не нужна. OPEN-3 |
| 6 | `ProblemParams.additionalProperties: true` — строгость принесена в жертву читаемости: набор ключей зависит от `code`, выразить это через 29 подсхем с `oneOf` и `discriminator` было бы нечитаемо | **Принято.** Компромисс назван явно — это и требуется |

### ASSUMPTION-01…11 агента

WebID как вендор · внутренний периметр и mTLS · **идемпотентные холды и версия баланса в S6** ·
**поиск по `idempotencyKey` в S8** · S5 отдаёт bid/ask · HMAC-SHA256 подпись вебхуков ·
нормализация лимитов в RUB и UTC-сутки · порог дрейфа абсолютный и симметричный · S7 только
информирует · S9 вызывается после фиксации заявки · в §7 нет кодов «order not found» и «user not found».

Два из них (03 и 04) агент пометил как **блокирующие**: без идемпотентности на стороне S6 и S8
корректная обработка таймаута финансовой мутации невозможна в принципе. Согласен — это первое,
что нужно подтвердить у владельцев этих сервисов.

---

## [10] 2026-08-07 — ОРКЕСТРАТОР — Сквозная проверка консистентности артефактов

Артефакты делали разные агенты параллельно. Чтобы расхождения находились автоматически, а не глазами
читателя, написан `tools/verify-docs.mjs` — он сверяет документы между собой.

| Группа проверок | Что именно сверяется |
|-----------------|----------------------|
| OpenAPI | все 10 файлов парсятся, объявляют 3.1, имеют `info` и `paths`/`webhooks` |
| Поверхность API | 7 обязательных эндпоинтов; 11 кодов ответа у `POST /v1/exchange-orders`; `Idempotency-Key` — обязательный заголовок (с разрешением `$ref`); приём `X-Correlation-Id` |
| Деньги | ни одно денежное поле не объявлено как `number`/`integer` во всех 10 спеках |
| Каталог ошибок | множества кодов в каноне §7, в `prototype/src/domain/errors.ts` и в основной спеке **совпадают**; прототип не изобретает лишних кодов |
| Gherkin | заголовок языка; все теги `@error-*` — реальные коды; не менее 1 happy и 5 negative; покрытие всех 8 обязательных кейсов брифа |
| Фикстуры | 6 ключевых чисел присутствуют и в каноне §10, и в фикстурах прототипа; ненулевой `held` у ETH в обоих |
| Mermaid | диаграммы присутствуют; нет кириллицы в идентификаторах узлов (подписи и текст сообщений — можно) |

**Результат: 97/97 PASS.**

### Ложные срабатывания собственного чекера — исправлены, а не подавлены

1. Проверка `Idempotency-Key` падала, потому что параметр объявлен через `$ref`, а чекер не резолвил
   ссылки. Добавлен резолвер; заодно проверка усилена до `in: header` и `required: true`.
2. Поля `total` в `KycDocumentMetaList`, `PairsResponse`, `LinkedWalletList` — это счётчики строк,
   а не деньги, и `integer` для них корректен. Правило разделено на строгий список денежных полей
   (флагуются и `number`, и `integer`) и неоднозначный (флагуется только `number`, потому что
   счётчик дробным не бывает).
3. Кириллица в тексте сообщений `sequenceDiagram` легитимна. Чекер теперь отбрасывает текст после
   первого двоеточия на строках-переходах.

Три «падения» оказались дефектами проверки, а не документов. Зафиксировано намеренно: инструмент
проверки — тоже артефакт и тоже может врать.

### Верификация прототипа

| Проверка | Результат |
|----------|-----------|
| `npm run typecheck` (strict) | без ошибок |
| `npm run verify:money` — 22 ассерта против чисел feature-файла | 22/22 PASS |
| `npm run verify:render` — SSR-рендер дерева компонентов, 17 ассертов | 17/17 PASS |
| `npm run build` | 64 модуля, 272 kB JS / 24 kB CSS |

---

## [11] 2026-08-07 — ОРКЕСТРАТОР — Открытые вопросы к заказчику

Ниже — то, что осознанно **не** решено внутри команды агентов, потому что требует решения бизнеса.
Каждый пункт имеет провизорное решение, то есть работа нигде не остановлена.

| # | Вопрос | Почему это важно | Провизорное решение |
|---|--------|------------------|---------------------|
| OPEN-1 | Граница суток для дневного лимита: UTC или локальное время резидента? | Пользователь-фикстура — резидент `AE`. При UTC он увидит сброс лимита в 04:00 по местному времени. Это обращения в поддержку и потенциальный вопрос комплаенса | UTC и нормализация в RUB. Требует подтверждения комплаенса |
| OPEN-2 | Порог дрейфа курса: единый 0.20 % или per-pair из S4? | Для `RUB→BTC` единый порог даст `RATE_CHANGED` почти на каждом подтверждении — экран станет неюзабельным | Единый 0.20 %; рекомендуем сделать per-pair |
| OPEN-3 | Нужен ли поиск заявки по `Idempotency-Key`? | Клиент, потерявший соединение сразу после `POST`, не может узнать `orderId`. История операций вне скоупа, но восстановление состояния — не история | Не добавлено. Рекомендуем `GET /v1/exchange-orders?idempotencyKey=…` |
| OPEN-4 | Обратный расчёт: «хочу получить ровно 100 USDT» | Поле «Получаю» read-only по BRD §7. Первый же такой запрос — ломающее изменение контракта | Не поддержан. Рекомендуем заложить поле `side` заранее |
| OPEN-5 | Годовые лимиты | S4 умеет `YEARLY_LIMIT_EXCEEDED`, кода в каталоге нет — пользователь увидит текст про месячный лимит | Схлопнуто в `LIMIT_EXCEEDED_MONTHLY` |
| OPEN-6 | Вендор KYC — это действительно WebID? | От вендора зависит маппинг полей; форма контракта сохранится в любом случае | Контракт спроектирован по модели WebID Solutions, помечено ASSUMPTION-01 |
| OPEN-7 | Идемпотентность на стороне S6 и S8 | Без неё корректная обработка таймаута финансовой мутации невозможна в принципе | Предполагается наличие. **Блокирующее допущение** |
| OPEN-8 | Минимальный уровень KYC для обмена | Сейчас зашит уровень 2 (`VERIFIED`) | Требует подтверждения комплаенса |

---

## [12] 2026-08-07 — ЗАКАЗЧИК — Второй раунд требований

Дословно полученные сообщения:

> по прототипу: весь блок aside убрать, т.к. в прототипе необходимо показать страницу обмена,
> то и область с балансами необходимо скрыть `<div class="balances">` а сами балансы выводит
> в выпадающем списке при выборе валюты, выпадающий список подтянуть по дизайну к остальным
> формам — привлечь Ui/Ux агента.
>
> Отдельно сделать url на свагер с апи и отдельно url на документацию по проекту. в виде wiki
> дизайн и обрмление можешь подсмотреть в `d:\Project\common_docs\`
>
> По замечаниям, не подтягиваются курсы, не получается совершить обмен.

> и не забываем что вёрстка прототипа должна быть адаптивной, и отображаться одинаково
> и на мобильных устройствах и в браузере

### Извлечённые требования

| # | Требование | Тип | Статус |
|---|-----------|-----|--------|
| R-12 | Убрать блок `<aside class="devpanel">` целиком | UI | Выполнено |
| R-13 | Скрыть блок `<div class="balances">` | UI | Выполнено |
| R-14 | Балансы выводить в выпадающем списке выбора валюты | UI | Выполнено |
| R-15 | Дропдаун привести к дизайну остальных форм, привлечь UI/UX-агента | Процесс + UI | Выполнено, спецификация — `UX-UI-Spec.md` §22 |
| R-16 | Отдельный URL со Swagger UI по API | Инфраструктура | Выполнено, см. `portal/` |
| R-17 | Отдельный URL с документацией в виде wiki, оформление по образцу `common_docs` | Инфраструктура | Выполнено, MkDocs Material |
| R-18 | **Не подтягиваются курсы** | Дефект | Исправлено, разбор в §14 |
| R-19 | **Не получается совершить обмен** | Дефект | Исправлено, разбор в §14 |
| R-20 | Вёрстка адаптивная, одинаково работает в браузере и на мобильных | UI | Выполнено, проверяется автоматически |

Референс `d:\Project\common_docs\` изучен: это **MkDocs Material** (`mkdocs.yml`, `material/overrides`,
раздача через nginx). В окружении уже установлены `mkdocs` 1.6.1, `mkdocs-material` 9.7.6,
`pymdown-extensions` 11.0 — портал сделан на том же стеке, а не на самописном генераторе.

---

## [13] 2026-08-07 — АГЕНТ «Code Reviewer» — Приёмка поставки

**Задача:** независимая приёмка всех артефактов и кода прототипа. Автопроверки агент намеренно
не перепроверял — только то, чего автоматика поймать не могла.

**Вердикт агента: «доработать».** 6 блокеров, 12 major, 10 minor, 5 nit.

Это самый ценный результат за всю работу: агент нашёл дефекты, которые прошли мимо 97 автоматических
сверок документов и мимо 39 проверок прототипа, потому что все они проверяли **согласованность**,
а не **поведение**.

### Блокеры и что с ними сделано

| # | Находка | Решение |
|---|---------|---------|
| **B-1** | `acceptRateChange` реализован наоборот контракту: при дрейфе сверх порога и `true` заявка создавалась по новому курсу, `expectedToAmount` игнорировался. Единственное место в поставке, где сделка могла исполниться по курсу, которого пользователь не видел, без верхней границы | **Исправлено.** `RATE_CHANGED` теперь возвращается при превышении порога **безусловно**; флаг действует только внутри порога. Формулировка в OpenAPI была права, код — нет |
| **B-2** | Дрейф курса при автообновлении по TTL не детектировался. Сравнение жило только в `createOrder`, то есть срабатывало лишь при submit. В сценарии `RATE_DRIFT` сумма менялась под курсором молча, без баннера, кнопка оставалась активной. **Главное требование BRD §8 не выполнялось** | **Исправлено.** `requestQuote` принимает `detectDrift`; при автообновлении сравнивает курс с предыдущей котировкой и поднимает `RATE_CHANGE` |
| **B-3** | Кнопка разблокировалась сама через 15 с, пока баннер ещё требовал принять курс: таймер продолжал тикать в фазе `RATE_CHANGED_PENDING_ACCEPT`, автообновление возвращало `QUOTE_READY`, а `rateChange` не сбрасывался | **Исправлено двумя изменениями:** таймер не работает в этой фазе, и `QUOTE_OK` сохраняет фазу ожидания принятия, если уведомление ещё активно |
| **B-4** | Серверные ошибки уровня поля стирались через один кадр: `LOCAL_ISSUE` безусловно обнулял слот, а `validateLocally` про лимиты не знал. Сценарий `LIMIT_HIT` визуально не работал вовсе | **Исправлено.** Заведены два слота: `localIssue` (пересчитывается) и `serverIssue` (живёт до изменения ввода). Дополнительно дневной лимит теперь проверяется и на клиенте |
| **B-5** | Число в сценарии дрейфа не совпадало с тем, что считает прототип (`105.448781` против `105.449735`), а проверка это скрывала: `verify-money.mjs` подставлял курс, которого код никогда не производит | **Исправлено.** Вместо множителя `0.9947` заведена таблица точных значений после дрейфа: `RUB/USDT → 0.010582010582`. Комментарий, утверждавший соответствие feature-файлу, был неверен и переписан |
| **B-6** | Payload `RATE_CHANGED` описан тремя разными способами; полей с суммами, на которых построен баннер, в контракте не было вовсе | **Исправлено.** Единое именование `quotedRate / currentRate / quotedToAmount / currentToAmount / driftPercent / thresholdPercent` в коде, OpenAPI и SDD. В `ProblemParams` добавлены обе суммы с обоснованием: пользователь принимает решение по сумме, а не по коэффициенту |

### Major — сделано

Бесконечный опрос упавшего сервиса (~3 запроса/с) → восстановление стало явным действием
пользователя, автоматических ретраев нет · бесконечный ре-рендер в `QUOTE_STALE` → `MARK_STALE`
и `TICK` больше не порождают новое состояние без изменения · строка комиссии показывала «0.35 %»
там, где реально удерживалось 2 % из-за `minFee` → выводится **фактический** процент ·
`canSubmit` игнорировал баннер → теперь учитывает · срок действия KYC не проверялся →
проверяется · `WALLET_FROZEN` не выдавался никогда → выдаётся по `restrictions` из S1 ·
идемпотентный ключ занимался только после успеха → занимается до начала работы и освобождается
при отказе; параллельный запрос с тем же ключом получает `IDEMPOTENCY_CONFLICT` · ключ не
ротировался при новой котировке → ротируется · не было строки «Итоговая сумма списания»
(BRD §4.11) → добавлена `Total debited` · дневной лимит не проверялся на клиенте → проверяется ·
инвариант I1 проверялся через `Number` → проверяется десятичной арифметикой, добавлена проверка I5 ·
Gherkin не связывался с прототипом → добавлен раздел соответствия в `docs/features/README.md`.

### Minor — сделано

Ввод «1000.» больше не даёт ошибку (использована `PARTIAL_INPUT_PATTERN`, которая раньше была
мёртвым кодом) · `assertQuoteInvariants` теперь действительно проверяет I5, `decimalPlaces`
перестал быть мёртвым кодом · «Paused — tap to refresh» заменено на «Paused — edit the amount»,
потому что обработчика на этом элементе нет · кнопка «Retry» теперь действительно повторяет ·
подпись таймера приведена к решению D-05 (`Rate updates in`) · `Balance:` → `Available:` ·
`Escape` не сбрасывает форму во время отправки · котировки вытесняются из хранилища ·
`SAME_ASSET_PAIR` больше не «недостижим»: молчаливый swap убран, вариант дизейблится с причиной ·
исправлена невалидная вложенность `<div>` внутри `<p>`.

### Что агент отметил как сделанное хорошо

Канонический контракт до запуска агентов · денежная дисциплина в `money.ts` (`Decimal` не утекает
наружу модуля, режимы округления названы поимённо) · у каждого решения названа цена · Compliance-First
обоснован через утечку информации подбором сумм, а не «так принято» · сага hold→order с компенсацией.

### Что не принято

- **Иконка валюты слева, а не справа (BRD §7).** Оставлено слева: UX-спецификация §17 и Design Brief
  располагают селектор слева, а сумму — справа, и это единственная раскладка, в которой длинное
  крипто-число не наезжает на элемент управления. Расхождение с буквой BRD зафиксировано осознанно.
- **`Ctrl/Cmd+S` для swap.** Оставлено `Alt+S`: `Ctrl+S` перехватывается браузером как «сохранить страницу».

---

## [14] 2026-08-07 — ОРКЕСТРАТОР — Разбор дефектов «не подтягиваются курсы» и «не получается обмен»

Первым делом воспроизвёл проблему, а не стал править по описанию. Браузерного инструмента в среде
нет, поэтому написан **jsdom-тест** (`prototype/scripts/verify-flow.tsx`): монтирует настоящее
приложение, печатает в настоящее поле, нажимает настоящую кнопку и проверяет то, что увидел бы
человек.

**Результат первого прогона:** ввод суммы → котировка строится, кнопка активируется, заявка
создаётся, `orderId` показан. То есть сама цепочка была жива, и «починка наугад» сломала бы
работающее.

**Настоящая причина.** Курс отображался **только как часть котировки**, а котировка строилась
только для валидной суммы. Следствия:

1. При открытии экрана информационный блок показывал `Current Rate —`. BRD §3 требует загружать
   актуальные курсы **при открытии**, BRD §4 — «видеть актуальный курс»; ни то, ни другое не
   обусловлено вводом суммы. Ровно это и выглядит как «курсы не подтягиваются».
2. При сумме ниже минимума пары (для `RUB→USDT` это 500 RUB) котировка не строилась вовсе, и
   пользователь не видел ни курса, ни причины — только неактивную кнопку. Ровно это и выглядит
   как «не получается совершить обмен».

**Исправление.** Введён индикативный курс, не зависящий от суммы:
`getIndicativeRate(from, to)` загружается при открытии экрана и при каждой смене пары, а сводка
показывает его, пока котировки нет. Это цена без фиксации — «ценник, а не обещание»; подтвердить
можно по-прежнему только котировку.

**Урок, который стоит зафиксировать.** SSR-проверка рендера и 97 сверок документов дали ложное
чувство покрытия: они проверяли, что экран отрисовывается и что документы согласованы, но ни одна
не проверяла, что экран **работает**. Тест поведения добавлен в обязательный набор
(`npm run verify:flow`) и включает мобильный режим.

---

## [15] 2026-08-07 — АГЕНТ «UX Architect + UI Designer» — Переработка селектора активов

**Задача:** убрать блок балансов и dev-панель, перенести балансы в выпадающий список, привести
список к дизайну остальных форм. Сохранить адаптивность.

**Артефакт:** новый нормативный **§22** в `docs/UX-UI-Spec.md` (старше §9.3/§15.3/§17.5 при
расхождении).

### Ключевые решения агента

| Решение | Обоснование агента | Оценка оркестратора |
|---------|--------------------|---------------------|
| Паттерн `combobox` + `listbox`, не `menu` | `menu` — для команд; здесь выбор значения с `aria-selected` | Принято |
| **Без зацикливания** стрелками | 5 активов; цикл маскирует край списка и при удержании стрелки выбирает не тот актив. Края — `Home`/`End` | Принято |
| Фокус физически остаётся на триггере, позиция — через `aria-activedescendant` | Стандартная практика для combobox | Принято |
| **Bottom-sheet обязателен ≤480px** | Клавиатура съедает ~40 % высоты и ломает якорный dropdown; лист попадает в зону большого пальца | Принято. Ветка проверяется автоматически в jsdom-тесте |
| Нулевой баланс (EUR) **не дизейблить** | `INSUFFICIENT_FUNDS` у поля объяснит точнее, чем немой disabled | Принято |
| `held` показывать только когда > 0, `total` — не показывать | Три числа в строке нечитаемы; `total` уходит в `title` | Принято |
| **Убрать молчаливый swap** при выборе того же актива | Он менял обе денежные величины без нажатия кнопки обмена — запрещено §2.1 спецификации | Принято. Заодно делает достижимым сценарий 13 Gherkin |
| Подвал панели с кнопкой `Switch to RUB → USDT`, когда все варианты недоступны | Иначе `from = EUR` — тупик (риск R-11) | Принято |

### Найденные проблемы контраста

Агент повторно применил приём, которым ранее разделял зелёный: две пары из его же прежней
спецификации не проходили WCAG AA и были заменены.

| Пара | Было | Стало |
|------|------|-------|
| Баланс в строке списка на hover-фоне `#F3F4F6` | `#6B7280` → **4.39** | `#4B5563` → **6.83** |
| Причина недоступности варианта | `#9CA3AF` → **2.54** | `#6B7280` → **4.83** |

Отдельно: у недоступной строки **нет `opacity`** — `#6B7280` под `opacity: .5` на белом даёт ~2.2.
Причина недоступности — единственное объяснение, почему вариант нельзя выбрать, и обязана читаться.

### Признанный регресс

Чтобы увидеть все пять балансов сразу, теперь нужно открыть список. Агент честно зафиксировал это
как регресс discoverability — риск **R-16** — и предложил проверить в первом же usability-тесте.
Компенсация: строка `Available:` в шапке блока показывает баланс активного актива без открытия
списка, а при ненулевом `held` дополняется `· 0.10 on hold`.

---

## [16] 2026-08-07 — АГЕНТ «Документационный портал» — Wiki и Swagger UI

**Задача (требования R-16, R-17):** два отдельных адреса — Swagger UI по API и wiki с документацией
проекта, оформление по образцу `d:\Project\common_docs\`.

**Разбор референса.** `common_docs` — проект на **MkDocs Material** (`mkdocs.yml`, `material/overrides`,
раздача через nginx). В окружении уже стояли `mkdocs` 1.6.1, `mkdocs-material` 9.7.6,
`pymdown-extensions` 11.0, поэтому портал сделан на том же стеке, а не на самописном генераторе.

**Артефакт:** `portal/` — 27 авторских файлов.

### Адреса

| Что | Команда | URL |
|-----|---------|-----|
| Wiki | `npm run wiki` | `http://127.0.0.1:8100/` |
| Swagger UI | `npm run api` | `http://127.0.0.1:8101/` |
| Собранный портал целиком | `npm run build && npm run serve` | `http://127.0.0.1:8080/` и `/swagger/` |

Порт 5173 намеренно не задействован — прототип должен работать одновременно с порталом.

### Ключевое решение: контент не дублируется

Страницы wiki — **однострочные обёртки** вида `--8<-- "docs/SDD.md"`; `pymdownx.snippets`
с `base_path` на корень репозитория подставляет исходник при сборке. Второй копии физически
не существует, расходиться нечему.

Имена файлов-обёрток подобраны так, чтобы относительные ссылки **внутри исходников**
(`./00-canonical-model.md`, `../BRD.md`, `./exchange-order.feature`) продолжали работать
без правки самих исходников. Копируются только не-текстовые артефакты — 10 YAML, сырой
`.feature`, вендорные JS/CSS; этим занимается `tools/sync.py`, встроенный в каждую команду.

**Оценка оркестратора:** это лучший из трёх возможных вариантов. Копирование markdown дало бы две
копии, расходящиеся через неделю; симлинки не переживают Windows и архивы. Цена решения — сборка
зависит от `pymdownx.snippets` и от того, что пути обёрток совпадают с путями исходников.

### Проверки агента

`python -m mkdocs build --strict` — **без единого warning** (строгий режим: битая ссылка роняет
сборку). HTTP 200 на 17 адресах. Mermaid проверен не только по HTML, но и headless-браузером:
12 диаграмм SDD и 1 диаграмма UX-спеки реально отрисованы в SVG. Swagger UI отдаёт ровно
10 спецификаций. Поиск: 507 документов, `lang: [ru, en]`. Тёмная тема проверена скриншотом.

### Перепроверка оркестратором

Я не принял отчёт на веру и прогнал сборку и адреса сам. Обе «нестыковки», которые я нашёл,
оказались дефектами **моих** проверок, а не работы агента:

1. Я искал `class="mermaid"` и получил 0 совпадений. На деле `mkdocs-minify-plugin` снимает кавычки
   с атрибутов: в собранном HTML 12 блоков `<pre class=mermaid>`. Диаграммы на месте.
2. Я нашёл `unpkg.com` в HTML Swagger UI и заподозрил CDN-зависимость. На деле основной источник —
   локальный `./vendor/swagger-ui-bundle.js`, а CDN подключается только в обработчике `onerror`,
   если каталог `vendor/` не собран. Ровно так агент и описал.

Записано намеренно: цена недоверия к отчёту — две ложные тревоги, цена доверия — необнаруженный
дефект. Первое дешевле, но проверять надо аккуратно.

### Честно названные ограничения

- Если удалить `portal/node_modules`, Swagger UI покажет предупреждающую плашку и уйдёт на CDN.
  В штатной конфигурации интернет не нужен.
- Ссылка «← Документация» на автономном Swagger UI (`:8101`) ведёт на `:8100`, то есть требует
  запущенной вики. В собранном портале это обычная относительная ссылка.
- Широкие диаграммы C4 L2/L3 Mermaid ужимает по ширине контейнера — мелковато. Material
  инициализирует Mermaid сам, и переопределить `useMaxWidth` без хака не выходит.

### Предложения агента, не реализованные сейчас

Разбить SDD и UX-спеку на разделы (245 КБ и 524 КБ HTML на страницу) · Dockerfile и nginx
по образцу `common_docs` для деплоя · Redoc как вторая подача спеки · `tools/verify-docs.mjs`
в CI перед сборкой портала. Все четыре разумны и относятся к эксплуатации, а не к тестовому заданию.

---

## [17] 2026-08-07 — ОРКЕСТРАТОР — Состояние поставки после второго раунда

| Проверка | Объём | Результат |
|----------|-------|-----------|
| `prototype: typecheck` | strict, `noUnusedLocals`, `noUnusedParameters` | без ошибок |
| `prototype: verify:money` | арифметика против чисел feature-файла, включая инварианты I1 и I5 | 23/23 |
| `prototype: verify:render` | SSR-рендер дерева и поздних состояний | 18/18 |
| `prototype: verify:flow` | jsdom: ввод, список активов, подтверждение, мобильный проход | 29/29 |
| `tools/verify-docs` | OpenAPI, каталог ошибок, фикстуры, Gherkin, Mermaid | 97/97 |
| `portal: mkdocs build --strict` | 0 warnings | собирается |
| dev-сервер прототипа | `/`, `/src/main.tsx`, `?scenario=RATE_DRIFT` | HTTP 200 |
| портал | 8 адресов, включая YAML спецификаций | HTTP 200 |

**Итого автоматических проверок: 167.**

### Что изменилось в самом подходе после второго раунда

До замечаний заказчика набор проверок состоял из сверок **согласованности**: совпадают ли коды
ошибок в трёх артефактах, те ли числа в фикстурах, валиден ли YAML. Все они проходили — и при этом
экран не показывал курс при открытии, а баннер смены курса не срабатывал при автообновлении.

Добавлен уровень проверки **поведения** (`verify:flow`): приложение монтируется в DOM, тест печатает
в поле, открывает список, нажимает кнопку и сверяет то, что увидел бы человек. Именно он теперь
ловит регрессии, которые сверки документов пропускают по своей природе.

---

## [18] 2026-08-07 — ЗАКАЗЧИК — Третий раунд: деплой и движение курса

Дословно:

> Отлично, готовим для деплоя на railway, и к курсу добавь кофициент, чтобы по истечении
> 15 секунд курс менялся. можно добавить один,

| # | Требование | Тип |
|---|-----------|-----|
| R-21 | Подготовить проект к деплою на **Railway** | Инфраструктура |
| R-22 | Добавить к курсу **коэффициент**, чтобы по истечении 15 секунд курс менялся; достаточно одного | Домен / прототип |

---

## [19] 2026-08-07 — ОРКЕСТРАТОР — Имитация движения рынка

### Проблема, которую закрывает требование

Курсы в фикстурах были статичны. Автообновление котировки по истечении TTL возвращало **ровно то же
число**, поэтому пятнадцатисекундная фиксация выглядела декоративной: по экрану невозможно было
понять, пересчиталась ли котировка или таймер просто крутится вхолостую. Требование заказчика
устраняет ровно это.

### Реализация

```
rate(t) = базовый курс × коэффициент ^ floor((t − старт сессии) / период окна)
```

Один коэффициент, как и просил заказчик. Период окна по умолчанию равен TTL котировки (15 с из §2),
то есть рынок двигается **ровно в тот момент**, когда истекает фиксация.

| Параметр | По умолчанию | Переопределение |
|----------|--------------|-----------------|
| Коэффициент | `0.9995` (−0.05 % за окно) | `?rateTickFactor=0.99` |
| Период окна | `15000 мс` | `?rateTickMs=3000` |
| Выключение | — | `?rateTick=off` |

### Главное решение: почему −0.05 %, а не больше

Величина коэффициента — не косметика, а выбор между двумя разными продуктами.

Порог вмешательства из §11 равен **0.20 %**. Коэффициент **выше** порога означал бы, что каждое
истечение TTL требует заново принять условия: каждые 15 секунд баннер, заблокированная кнопка,
явное подтверждение. Формально это демонстрировало бы BRD §8 на главном пути, фактически —
превратило бы защитный механизм в шум, который пользователь научится прокликивать не читая,
и сломало бы обещание «обмен за несколько секунд» из BRD §2.

Поэтому выбран коэффициент **ниже** порога: сумма получения по истечении окна заметно меняется,
но пересчёт тихий. Случай сверх порога никуда не делся и демонстрируется отдельно —
`?scenario=RATE_DRIFT` (−0.53 %) либо `?rateTickFactor=0.99`.

Цена решения: чтобы увидеть требование принять новые условия, нужно специально включить сценарий.
Считаю это правильным размещением: редкое и важное событие не должно происходить постоянно.

### Побочный эффект, найденный до сдачи

Движущийся курс сломал бы то, что раньше работало: индикативный курс загружался **один раз**
при открытии экрана. На простаивающей вкладке он устарел бы, и первая же котировка после ввода
суммы не совпала бы с числом, которое пользователь видел в сводке минуту назад.

Исправлено: пока котировки нет, индикативный курс перезапрашивается раз в окно. Как только
котировка построена, опрос прекращается — иначе на экране одновременно жили бы две разные цены.

### Ограничения

Накопление ограничено 400 окнами: вкладка, оставленная на ночь, иначе показала бы абсурдный курс.
Коэффициент применяется поверх сценарного дрейфа, а не вместо него.

### Проверки

Добавлены три автоматические проверки в `verify:flow`: курс меняется после истечения окна
(окно укорочено до 300 мс, чтобы тест не ждал 15 секунд); `?rateTick=off` замораживает рынок;
замороженный курс равен опубликованному фикстурному. Основные проверки сумм выполняются
с `?rateTick=off` — иначе ассерты против чисел feature-файла зависели бы от того, сколько
секунд длилась сборка теста.

---
